spring:
  application:
    name: authorization-server
  security:
    oauth2:
      authorizationserver:
#        issuer: http://localhost:8080
        client:
          public-client:
            registration:
              client-id: "public-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
#                - "none"
                - "client_secret_basic"
#                - "client_secret_post"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://localhost:3000/callback"
#                - "http://localhost:3000"
              scopes:
                - "openid"
                - "profile"
                - "read"
                - "write"
#                - "email"
#            require-authorization-consent: true
#            require-proof-key: true
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - openid
#              - profile
#              - email

server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE
