spring:
  application:
    name: authorization-server
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email

server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE
