spring:
  application:
    name: authorization-server
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080

server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE