spring:
  application:
    name: client-application
#  security:
#    oauth2:
#      client:
#        registration:
#          oauth2-test-client:
#            provider: spring
#            client-id: oauth2-test-client
#            client-secret: client-secret
#            client-authentication-method: client_secret_basic
#            authorization-grant-type: client_credentials
#            scope: read
#        provider:
#          spring:
#            token-uri: http://localhost:8080/oauth2/token

server:
  port: 3000

logging:
  level:
    org.springframework.security: TRACE